--<ScriptOptions statementTerminator=";"/>

CREATE TABLE ITEM_RESOURCE (
		ITEM_RESOURCE_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		RESOURCE_NAME VARCHAR(100) NOT NULL,
		ITEM_ID INTEGER NOT NULL,
		EXTENSION VARCHAR(10) NOT NULL,
		CONTENT_TYPE VARCHAR(30) NOT NULL,
		RES_PATH VARCHAR(200) NOT NULL
	);

CREATE TABLE LOCATION (
		LOCATION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		NAME VARCHAR(50) NOT NULL,
		USER_ID INTEGER NOT NULL,
		COUNTRY_ID INTEGER,
		ADDRESS VARCHAR(150),
		ZIPCODE VARCHAR(15),
		REGION_ID INTEGER,
		CITY_ID INTEGER,
		CITY_AREA_ID INTEGER
	);

CREATE TABLE CITY (
		CITY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		CITY_NAME VARCHAR(100) NOT NULL,
		REGION_ID INTEGER,
		COUNTRY_ID INTEGER
	);

CREATE TABLE COUNTRY (
		COUNTRY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		COUNTRY_NAME VARCHAR(100) NOT NULL
	);

CREATE TABLE CITY_AREA (
		CITY_AREA_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		CITY_ID INTEGER NOT NULL,
		CITY_AREA_NAME VARCHAR(100) NOT NULL
	);

CREATE TABLE APPUSER (
		USER_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		NAME VARCHAR(50) NOT NULL,
		USER_NAME VARCHAR(50) NOT NULL,
		PASSWORD VARCHAR(150) NOT NULL,
		SECRET VARCHAR(15),
		EMAIL VARCHAR(100) NOT NULL,
		REGISTERED DATE NOT NULL,
		MODIFIED DATE
	);

CREATE TABLE ITEM (
		ITEM_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		ITEM_NAME VARCHAR(100) NOT NULL,
		ANNOUNCER_ID INTEGER NOT NULL,
		CATEGORY_ID INTEGER NOT NULL,
		PUBLISHED DATE NOT NULL,
		MODIFIED DATE NOT NULL,
		PRICE DECIMAL(10 , 2) NOT NULL,
		CONTACT_NAME VARCHAR(100) NOT NULL,
		CONTACT_EMAIL VARCHAR(100) NOT NULL,
		ITEM_ACTIVE SMALLINT DEFAULT 1 NOT NULL,
		EXPIRATION DATE NOT NULL,
		DESCRIPTION VARCHAR(4000) NOT NULL,
		LOCATION_ID INTEGER NOT NULL
	);

CREATE TABLE REGION (
		REGION_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		COUNTRY_ID INTEGER NOT NULL,
		REGION_NAME VARCHAR(100) NOT NULL
	);

CREATE TABLE CATEGORY (
		CATEGORY_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		PARENT_CATEGORY_ID INTEGER,
		CATEGORY_NAME VARCHAR(100) NOT NULL,
		POSITION INTEGER NOT NULL,
		CAT_ENABLED SMALLINT NOT NULL
	);

CREATE TABLE ITEM_COMMENT (
		ITEM_COMMENT_ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
		ITEM_ID INTEGER NOT NULL,
		PUBLISHED DATE NOT NULL,
		TITLE VARCHAR(100) NOT NULL,
		AUTHOR_NAME VARCHAR(100) NOT NULL,
		AUTHOR_EMAIL VARCHAR(100) NOT NULL,
		BODY VARCHAR(4000) NOT NULL,
		USER_ID INTEGER
	);

CREATE TABLE ITEM_LOCATION (
		ITEM_ID INTEGER NOT NULL,
		LOCATION_ID INTEGER NOT NULL
	);
	
CREATE UNIQUE INDEX SQL150422230409370 ON ITEM (ITEM_ID ASC);

CREATE UNIQUE INDEX SQL150422223535410 ON REGION (REGION_ID ASC);

CREATE UNIQUE INDEX SQL150422224940710 ON CATEGORY (CATEGORY_ID ASC);

CREATE UNIQUE INDEX SQL150423000430890 ON ITEM_RESOURCE (ITEM_RESOURCE_ID ASC);

CREATE UNIQUE INDEX SQL150422212339610 ON CITY (CITY_ID ASC);

CREATE UNIQUE INDEX SQL150422224230330 ON COUNTRY (COUNTRY_ID ASC);

CREATE UNIQUE INDEX SQL150422224412560 ON CITY_AREA (CITY_AREA_ID ASC);

CREATE UNIQUE INDEX SQL150423001615740 ON ITEM_COMMENT (ITEM_COMMENT_ID ASC);

CREATE UNIQUE INDEX SQL150423002352120 ON LOCATION (LOCATION_ID ASC);

CREATE UNIQUE INDEX SQL150423003006650 ON APPUSER (USER_ID ASC);

CREATE UNIQUE INDEX SQL150424142442640 ON ITEM_LOCATION (ITEM_ID ASC, LOCATION_ID ASC);

ALTER TABLE APPUSER ADD CONSTRAINT USER_PK PRIMARY KEY (USER_ID);

ALTER TABLE ITEM_COMMENT ADD CONSTRAINT ITEM_COMMENT_PK PRIMARY KEY (ITEM_COMMENT_ID);

ALTER TABLE ITEM ADD CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID);

ALTER TABLE REGION ADD CONSTRAINT REGION_PK PRIMARY KEY (REGION_ID);

ALTER TABLE CITY_AREA ADD CONSTRAINT CITY_AREA_PK PRIMARY KEY (CITY_AREA_ID);

ALTER TABLE CATEGORY ADD CONSTRAINT CATEGORY_PK PRIMARY KEY (CATEGORY_ID);

ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_PK PRIMARY KEY (LOCATION_ID);

ALTER TABLE ITEM_RESOURCE ADD CONSTRAINT ITEM_RESOURCE_PK PRIMARY KEY (ITEM_RESOURCE_ID);

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (COUNTRY_ID);

ALTER TABLE CITY ADD CONSTRAINT CITY_PK PRIMARY KEY (CITY_ID);

ALTER TABLE ITEM_LOCATION ADD CONSTRAINT ITEM_LOCATION_PK PRIMARY KEY (ITEM_ID, LOCATION_ID);


INSERT INTO country (country_name) values('Argentina');
INSERT INTO country (country_name) values('Brasil');
INSERT INTO country (country_name) values('Chile');
INSERT INTO country (country_name) values('Equador');
INSERT INTO country (country_name) values('Estados Unidos');
INSERT INTO country (country_name) values('Uruguai');
